### ISSUE TITLE
Error when generating "remessa" to code bank 001

### ISSUE THREAD

**Issue by tutusouza** [banco-br/nodejs-cnab#27]
generateRemessaCnab Error: ENOENT: no such file or directory, open './node_modules/@banco-br/cnab_yaml/cnab400/001/remessa/trailer_arquivo.yml'
    at Object.openSync (<node_internals>/fs.js:438:3)
    at Object.readFileSync (<node_internals>/fs.js:343:35)
    at readYaml (c:\web\cnabMiccon\node_modules\@banco-br\nodejs-cnab\src\utils.ts:146:27)
    at _loop_1 (c:\web\cnabMiccon\node_modules\@banco-br\nodejs-cnab\src\remessa.ts:24:24)
    at generateRemessaCnab (c:\web\cnabMiccon\node_modules\@banco-br\nodejs-cnab\src\remessa.ts:13:16)
    at Object.<anonymous> (c:\web\cnabMiccon\index.js:70:23)
    at Module._compile (<node_internals>/internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (<node_internals>/internal/modules/cjs/loader.js:712:10)
    at Module.load (<node_internals>/internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12) {errno: -4058, syscall: 'open', code: 'ENOENT', path: './node_modules/@banco-br/cnab_yaml/cnab400/001/remessa/trailer_arquivo.yml', stack: 'Error: ENOENT: no such file or directory, ope…eLoad (internal/modules/cjs/loader.js:539:12)', …}

It looks like you're talking about a file.

**Comment by mariohmol** [comment]
foi mal.. faz tempo que não mexo nesse projeto, conseguiu evoluir?

**Comment by natanfoleto** [comment]
@tutusouza Estava usando a biblioteca e tive o mesmo problema, reparei que que quando o parâmetro bankCode é enviado com a string '001' que é referente ao banco do brasil, ele tenta encontrar o arquivo trailer_arquivo.yml dentro da pasta do banco do brasil, que não existe. Se você passar outro bankCode, ele funciona, pois o arquivo existe na pasta dos outros bancos. Uma solução alternativa é você copiar o arquivo de um banco dentro do outro que falta, mas você precisa saber todas as configurações do banco do brasil pra quando for gerar ele não gerar errado.

OBS: Se você abrir as pastas da biblioteca na node_modules, vai poder visualizar os arquivos e saber qual banco tem e qual não tem o arquivo trailer_arquivo.yml

Espero que tenha ajudado.

**Comment by mariohmol** [comment]
boa!! consegue nos enviar um PR?
